### ISSUE TITLE
Cannot handle large datasets?

### ISSUE THREAD

**Issue by denny64** [himynameisdave/svelte-frappe-charts#13]
What is the largest dataset that can be handled? I tried putting in 8000 data points in the array and it didn't work. Limiting that same dataset to less worked though...

**Comment by himynameisdave** [comment]
@denny64 I'm willing to bet that this is a bottleneck in the underlying [`frappe-charts`](https://frappe.io/charts) library, although I could be wrong. There might be other variables at play here, such as what browser / hardware you're running it on.

If possible, please post your dataset / setup / [codesandbox](https://codesandbox.io/) link so that I can investigate it further. Thanks!

**Comment by himynameisdave** [comment]
I've investigated this a bit more, and here are my findings:
- It appears as though there is a bit of a ceiling before performance starts to drop off (I tried with 8000+ data points).
- It seems to also appear when just using `frappe-charts` directly.

I am going to close this because it is unrelated to this library, although I encourage you to file an issue with `frappe-charts` and link back to here. Keep in mind that the frappe team is working on a version 2 of that library which will hopefully fix a lot of these issues. 

Feel free to file another issue if you have some examples of bottlenecks in this library.
