### ISSUE TITLE
How to set Chart Title, Axis Labels?

### ISSUE THREAD

**Issue by davidscottmills** [himynameisdave/svelte-frappe-charts#27]
Per the Frappe configuration documentation, you should be able to set a [title](https://frappe.io/charts/docs/reference/configuration#title). I'm not able to see if or how this is being done in the base component. Could you add this to the wrapper?

**Comment by himynameisdave** [comment]
Hey @davidscottmills, thanks for filing this issue!

You are correct about the `title` attribute -- this was an oversight on my part, as when I originally wrote this wrapper I don't think `title` existed in [`frappe-charts`](https://github.com/frappe/charts) yet. Unfortunately there is no `CHANGELOG` for that library, and the [release notes](https://github.com/frappe/charts/releases) often don't contain info about new features/props like this one. 😕 

This is easy to implement, we'd just need to:
- Add `title` as an `export` prop [here](https://github.com/himynameisdave/svelte-frappe-charts/blob/6c7c3af7a9df55ef55b3685c03a3b86d3ec37cab/src/components/base.svelte#L16).
- Include it when initializing the chart [here](https://github.com/himynameisdave/svelte-frappe-charts/blob/6c7c3af7a9df55ef55b3685c03a3b86d3ec37cab/src/components/base.svelte#L62).

Feel free to open a PR if you are feeling ambitious, otherwise I'll try to get to it this weekend. 💪 

_Also:_ The title of this issue mentions Axis Labels as well -- are there any other ones that the library is missing?

**Comment by davidscottmills** [comment]
Thanks for taking care of this! Do you have plans for when you'll release a new npm package?

**Comment by himynameisdave** [comment]
@davidscottmills should be sometime today, just wanted to investigate #26 and see if I can bundle any required changes from that issue into the same release 👍

**Comment by himynameisdave** [comment]
@davidscottmills here ya go: https://github.com/himynameisdave/svelte-frappe-charts/releases/tag/v1.4.0

**Comment by davidscottmills** [comment]
@himynameisdave Thanks! As far as the axis labels go, I don't think Frappe Charts has the ability to add axis labels. Hopefully they'll add this in the future.
