### ISSUE TITLE
Error when refreshing the page

### ISSUE THREAD

**Issue by deb-dasit** [himynameisdave/svelte-frappe-charts#37]
Hi,
I'm getting **Error: <rect> attribute width: A negative value is not valid. ("-3.1999999999999993")** when refreshing the page or redirecting from another page.
I tried to render it in accordion as well in normal html body, but getting same issue.
![image](https://user-images.githubusercontent.com/3907017/118564770-8cc6a600-b78e-11eb-991b-a024997dae32.png)
Please help.

**Comment by himynameisdave** [comment]
Hi @deb-dasit! 

It looks like this error is originating from the [`frappe-charts`](https://github.com/frappe/charts) library based on the error messages. Please feel free to [file this issue over there](https://github.com/frappe/charts/issues/new), as they will have a better idea of what the issue is.

If the issue is related to Svelte in some way, feel free to notify me and we can reopen this issue and take a look! 👍

**Comment by deb-dasit** [comment]
Thanks @himynameisdave and apology for delay response. 
I have replaced the frappe-charts (svelte) with chartjs(svelte).
