### ISSUE TITLE
Could we have more examples?

### ISSUE THREAD

**Issue by drannex42** [himynameisdave/svelte-frappe-charts#8]
This may just be an oversight on my part - but I am not understanding how I can pass a series of configs to the Chart item? 

Instead of passing `type="line"` in the `<Chart>` item, is it possible to just pass `<Chart config={config}>` where `let config = {type: 'line'}`?

**Comment by drannex42** [comment]
Another question, related, is there a method to trigger a data update from this plugin? I see base.svelte you have `afterUpdate(() => chart.update(data));` so it should be able to process new incoming data, but how would you trigger that event?

**Comment by himynameisdave** [comment]
Hi, thank you for your comment!

As is [outlined in the documentation for `frappe-charts`](https://frappe.io/charts/docs#usage), you are able to pass multiple datasets in the `data` prop, via `data.datasets` (which is an array of datasets).

This component is meant to act as a wrapper around `frappe-charts`, which is why the props mirror those passed to a `Chart` instance there. This means that things like `type="line"` or `title="My chart"` are passed in directly. `frappe-charts` [does not support passing a `config`](https://frappe.io/charts/docs/reference/configuration) prop, so this wrapper does not / will not support that, however as you can see in the docs, each `dataset` can have its own `chartType`, which might be what you're looking for.
